title: Extreme Sports
email: m.ravanov@gmail.com
destination: docs
description: Site for extreme sports
baseurl: "/Extreme_Sports"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Marf_72
github_username: MartinRavanov72

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - docs
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - gulpfile.js
  - theme-personal
